### ISSUE TITLE
Missing a few methods

### ISSUE THREAD

**Issue by Shazwazza** [StefH/ReflectionBridge#1]
So far this is very helpful for porting over some code but it's missing a few methods like:

IsSealed
IsAbstract

**Comment by StefH** [comment]
I can add these methods, or you can create a pull request.

However. Althought this helper library works fine for porting old code to the new .net core, its maybe better to convert you projects te other way around.

See some details here https://github.com/davidfowl/NetStandard/issues/4

**Comment by Shazwazza** [comment]
Yup I will do, just needed to log this info first, will find time tomorrow. Thx for the info!

**Comment by Shazwazza** [comment]
I'll close this issue now, have submitted a PR.

I actually didn't realize that there was a GetTypeInfo() method on Type from .Net 4.5+ so that is certainly one way to tackle code portability. For now we are porting a very large project which is going to take quite a lot of time so we'll stick to using ReflectionBridge for now until we we have time to do a cleanup.
