### ISSUE TITLE
Nuget package ?

### ISSUE THREAD

**Issue by ahmad-moussawi** [StefH/ReflectionBridge#5]
Is it allowed to copy the classes in my own project ?, since there is no nuget package to include

**Comment by ahmad-moussawi** [comment]
oops my fault, found it https://www.nuget.org/packages/ReflectionBridge/
maybe you should put this in the README.md

**Comment by StefH** [comment]
Good point. I will add a NuGet badge in the readme

**Comment by StefH** [comment]
;-)

I just found out that I already have a badge in the readme !

**Comment by ahmad-moussawi** [comment]
:D
