### ISSUE TITLE
Is it compatible with System.Reflection.TypeExtensions ?

### ISSUE THREAD

**Issue by ahmad-moussawi** [StefH/ReflectionBridge#6]
When using this two libraries together am getting this:

`
error CS0121: The call is ambiguous between the following methods or properties: 'System.Reflection.TypeExtensions.GetGenericArguments(System.Type)' and 'ReflectionBridge.Extensions.ReflectionBridgeExtensions.GetGenericArguments(System.Type)`

when building using `netstandard1.3`

**Comment by StefH** [comment]
Did you try to define *NETSTANDARD* on your main project?

**Comment by ahmad-moussawi** [comment]
Nop, do I need to define it ?

**Comment by StefH** [comment]
Actually I think you need to add `REFLECTIONBRIDGE` as define. Can you try that ?

**Comment by ahmad-moussawi** [comment]
Yes sure, I will try this

**Comment by angularsen** [comment]
I got this error on `GetMethods(this Type)` on a WindowsRuntimeComponent project. My workaround was to rename it to `GetDeclaredMethods(this Type)`.
