### ISSUE TITLE
Feature request: Add missing methods (Type.GetProperty and Type.IsInstanceOfType)

### ISSUE THREAD

**Issue by AtricoSoftware** [StefH/ReflectionBridge#7]
Please consider adding

Type.GetProperty
Type.IsInstanceOfType

https://msdn.microsoft.com/en-us/library/system.type.getproperty(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.type.isinstanceoftype(v=vs.110).aspx

**Comment by StefH** [comment]
Type.IsInstanceOfType has a substitution. System.Reflection.TypeExtensions has a replacement

**Comment by StefH** [comment]
All is already supported. See the \examples.
