### ISSUE TITLE
Make the library part of Theraot library

### ISSUE THREAD

**Issue by NN---** [StefH/ReflectionBridge#9]
There is a library which includes all polyfills for legacy frameworks.
This code should be there instead of separate library.
https://github.com/theraot/Theraot

**Comment by StefH** [comment]
Good idea. I will take a look.

**Comment by NN---** [comment]
Btw, I have an improved version of your code with more methods:
https://github.com/NN---/CodeJam/blob/legacy_dotnet_targetting/CodeJam.Main/Targeting/NetCore/TypeExtensions.cs

If you are willing to submit PR for this library, it would be great !

**Comment by StefH** [comment]
You can submit a PR in this library if you like.

Or do you mean that I need to submit a PR in your library?

**Comment by NN---** [comment]
IMO the best is to make an effort and put it into https://github.com/theraot/Theraot .

**Comment by NN---** [comment]
Done.
https://github.com/theraot/Theraot/issues/85
